### PR TITLE
Market: fix REST responses

### LINKED ISSUE #21: Market unsubscribe result type
Both unsubscribe's should result with `()` and now results with `String`.
Comply with yaml which specifies`204` code

### PR DESCRIPTION
**Pull request by tworec**
It breaks compatibility of Market API, so **not to be merged before `Alpha.3`**.

fixes #21 
golemfactory/yagna#765 depends on this PR.

### CODE REVIEW

**Review by nieznanysprawiciel — COMMENTED** [review]
Requires change in ya-client, because it returns String either

**Comment by tworec** [comment]
pls check now

**Review by nieznanysprawiciel — DISMISSED** [review]

**Review by jiivan — APPROVED** [review]
lgtm, but IMO it should be marked more visibly as not ready for merge (either draft type or WIP in title?)

**Comment by tworec** [comment]
> lgtm, but IMO it should be marked more visibly as not ready for merge (either draft type or WIP in title?)

I will merge it to the `event-api/master` not to break `master`

**Pull request merged**
