### PR TITLE
Payment: Additional properties for Account model

### PR DESCRIPTION
**Pull request by Wiezzel**
Added `driver`, `network`, and `token` properties necessary for simultaneous mainnet/testnet support.

### CODE REVIEW

**Review by stranger80 — CHANGES_REQUESTED** [review]
Do you want to bump up a version number in yaml (1.6.2 I guess, as the new fields shouldn't break a "tolerant reader" client, so in that respect the update is backwards compatible)?

**Review by stranger80 — DISMISSED** [review]
Cheers!

**Comment by Wiezzel** [comment]
Added `send` and `receive` flags to avoid re-defining this struct in the main repo (this fields are used internally).

**Review by maaktweluit — COMMENTED** [review]
LGTM!

**Review by maaktweluit — APPROVED** [review]
LGTM!

**Pull request merged**
