### PR TITLE
API key authorization token.

### PR DESCRIPTION
**Pull request by pwalski**
API key authorization token. WebSocket endpoints authorized using API key.

Resolves https://github.com/golemfactory/yagna/issues/2510

Linked with https://github.com/golemfactory/yagna/pull/2504

### CODE REVIEW

**Comment by pwalski** [comment]
Updated all WebSocket endpoints with new shared security schema.
Both `net` `v1` and `v2` were updated, because `v2` is only about different path.

**Review by prekucki — CHANGES_REQUESTED** [review]
```
$ npm i -g @quobix/vacuum
$ vacuum lint -d -e -s net-api.yaml
```
### Operations Issues


|Line / Column | Severity | Message  |Path       |
|---------------------|-------------|----------------|------------|
|(220:7)       | error    | the 'get' operation at path '/net/{networkId}/tcp/{ip}/{port}' does not contain an operationId | $.paths./net/{networkId}/tcp/{ip}/{port}.get |

```
217 |       WebSocket endpoint for establishing a TCP connection to `{ip}:{port}`.
218 |     get:
219 |       security:
220 |         - app_key: []
221 |         - app_key_param: []
```

**Comment by prekucki** [comment]
```
$ vacuum lint -d -e -s gsb-api.yaml
```

### Schemas Issues

```
Line / Column | Severity | Message                                                | Path                                   
(36:11)       | error    | a `$ref` cannot be placed next to any other properties | $.components.responses.ServicesResponse


33 |             WebSocket endpoint allows to listen on incoming GSB messages.
34 |             "
35 |           $ref: "#/components/responses/ServicesResponse"
36 |           headers:
37 |             Location:

```

**Comment by pwalski** [comment]
Market API does not pass this linter too. 
I tried to fix it and add linter to CI, but [workaround for "a `$ref` cannot be placed next to any other properties"](https://github.com/swagger-api/swagger-editor/issues/1184#issuecomment-422044132) based on `allOf` does not work for two parameters (first one):
```
Line / Column | Severity | Message                                                                           | Path
(510:11)      | error    | the `get` operation at path `/agreements` contains a parameter with no `in` value | $.paths./agreements.get.parameters


507 |           schema:
508 |             $ref: '#/components/schemas/AgreementState'
509 |         - allOf:
510 |            - $ref: 'common.yaml#/parameters/afterTimestamp'
511 |           name: afterDate
```
[market-api.yaml.diff.tar.gz](https://github.com/golemfactory/ya-client/files/10996098/market-api.yaml.diff.tar.gz)

Fixing all lints is not a goal of this PR, so I dropped it.

**Review by prekucki — APPROVED** [review]

**Pull request merged**
