### PR TITLE
Updated Payment API specs to reflect current code state.

### PR DESCRIPTION
**Pull request by Wiezzel**

### CODE REVIEW

**Review by stranger80 — COMMENTED** [review]
OK, looks good, thanks for the clarifications in comments.
Would you like to bump the API/YAML version to 1.6.3, pls?

**Comment by Wiezzel** [comment]
@stranger80 
> Would you like to bump the API/YAML version to 1.6.3, pls?

Done.

**Review by pnowosie — APPROVED** [review]

**Comment by stranger80** [comment]
Approved.

**Review by stranger80 — APPROVED** [review]
Approved.

**Review by maaktweluit — APPROVED** [review]
LGTM!

**Pull request closed without merging**
